# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6313320e9fc5018499a28ddfc16a9aac6f1df61d6e19aae0bc0d637319b239fad2c6b4f8b45cf5aed8a0a5d21eebaf1e16fe127294de28d8f42dbd1c3fb35106

test:
  secret_key_base: 944caadb606adbd036814f9a39a4c176275431e243f76326176001cca8d2a980c5f35c4ac2aa1dab8d548d79a8938c9727ca7ff164b110446f89a75bd4792f45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
